//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleResultado
    {
        public int Id { get; set; }
        public string ExamenResultado { get; set; }
        public string Observacion { get; set; }
        public int ResultadoId { get; set; }
        public int ParametroId { get; set; }
    
        public virtual Resultado Resultado { get; set; }
        public virtual Parametro Parametro { get; set; }
    }
}
